version: '3'

services:
  tv-fetcher:
    build: .
    ports:
      - "8081:8081"  # WebSocket API
      - "9100:9100"  # Prometheus метрики
    environment:
      - TV_API_PROXY=
      - TV_API_TIMEOUT_MS=10000
      - SUBSCRIPTIONS=[{"symbol":"BINANCE:BTCUSDT","timeframe":"1"},{"symbol":"BINANCE:ETHUSDT","timeframe":"5"}]
      - BACKEND_ENDPOINT=
      - BACKEND_API_KEY=
      - WEBSOCKET_PORT=8081
      - WEBSOCKET_ENABLED=true
      - METRICS_PORT=9100
      - LOG_LEVEL=info
      - LOG_FILE=/app/logs/tv-fetcher.log
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped 